# Generated by Django 3.2 on 2022-07-04 11:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(blank=True, default=users.models.unique_id, max_length=5, null=True, unique=True, verbose_name='ID'),
        ),
    ]
