# Generated by Django 3.2 on 2022-07-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, choices=[('director', 'Директор'), ('manager', 'Менеджер'), ('accountant', 'Бухгалтер'), ('electric', 'Электрик'), ('plumber', 'Сантехник')], default='director', max_length=16, verbose_name='Роль'),
        ),
    ]
