# Generated by Django 3.2 on 2022-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_remember_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('is_active', 'Активен'), ('new', 'Новый'), ('disable', 'Отключен')], default='new', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='viber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Viber'),
        ),
    ]
