# Generated by Django 3.2 on 2022-08-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220722_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
