# Generated by Django 3.2 on 2022-08-18 18:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallery/', verbose_name='Изображение')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Об услуге',
                'verbose_name_plural': 'Об услугах',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название документа')),
                ('document', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg'])], verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='gallery/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=True, verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('keywords', models.TextField(verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'SEO-блок',
                'verbose_name_plural': 'SEO-блоки',
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.seo', verbose_name='SEO-блок')),
            ],
            options={
                'verbose_name': 'Страница наших услуг',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_1', models.ImageField(upload_to='gallery/', verbose_name='Слайд 1')),
                ('slide_2', models.ImageField(upload_to='gallery/', verbose_name='Слайд 2')),
                ('slide_3', models.ImageField(upload_to='gallery/', verbose_name='Слайд 3')),
                ('header', models.CharField(blank=True, max_length=64, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Краткий текст')),
                ('show_urls', models.BooleanField(default=True, verbose_name='Показывать ссылки на приложения')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.seo', verbose_name='SEO-блок')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Краткий текст')),
                ('url', models.URLField(verbose_name='Ссылка на коммерческий сайт')),
                ('full_name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('location', models.CharField(max_length=128, verbose_name='Локация')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('map', models.TextField(verbose_name='Код карты')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.seo', verbose_name='SEO-блок')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('header', models.CharField(blank=True, max_length=64, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainpage', verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Краткий текст')),
                ('avatar', models.ImageField(upload_to='gallery/', verbose_name='Фото директора')),
                ('additional_header', models.CharField(max_length=64, verbose_name='Дополнительный заголовок')),
                ('additional_text', models.TextField(verbose_name='Дополнительный краткий текст')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.seo', verbose_name='SEO-блок')),
            ],
            options={
                'verbose_name': 'О нас',
            },
        ),
    ]
