# Generated by Django 3.2 on 2022-07-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='page_id',
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default=None, max_length=64, verbose_name='Название документа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='block',
            name='header',
            field=models.CharField(blank=True, max_length=64, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='header',
            field=models.CharField(blank=True, max_length=64, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='text',
            field=models.TextField(blank=True, verbose_name='Краткий текст'),
        ),
    ]
