# Generated by Django 3.2 on 2022-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220716_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gallery/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.TextField(verbose_name='Keywords'),
        ),
    ]
