# Generated by Django 3.2 on 2022-07-18 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220718_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutservice',
            name='page_id',
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg'])], verbose_name='Документ'),
        ),
    ]
