# Generated by Django 3.2 on 2022-08-18 18:10

import crm.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер квартиры')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='Площадь (кв.м.)')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('description', models.TextField(verbose_name='Описание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('type_master', models.CharField(choices=[('any', 'Любой специалист'), ('electric', 'Электрик'), ('plumber', 'Сантехник')], default='any', max_length=16, verbose_name='Тип мастера')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('complete', 'Выполнена')], default='new', max_length=16, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Изображение 5')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=crm.models.invoice_number, unique=True, verbose_name='Номер квитанции')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('is_held', models.BooleanField(default=True, verbose_name='Проведена')),
                ('status', models.CharField(choices=[('paid', 'Оплачена'), ('p_paid', 'Частично оплачена'), ('unpaid', 'Неоплачена')], default='unpaid', max_length=16, verbose_name='Статус')),
                ('date_with', models.DateField(default=django.utils.timezone.now, verbose_name='Период с')),
                ('date_before', models.DateField(default=django.utils.timezone.now, verbose_name='Период до')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Квитанция',
                'verbose_name_plural': 'Квитанции',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('income_expense', models.CharField(choices=[('income', 'Приход'), ('expense', 'Расход')], default='income', max_length=16, verbose_name='Приход/Расход')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128, verbose_name='Тема сообщения')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('is_debt', models.BooleanField(default=False, verbose_name='Владельцам с задолженностями')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=crm.models.meter_reading_number, unique=True, verbose_name='Номер показания')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('accounted', 'Учтено'), ('paid', 'Учтено и оплачено'), ('zero', 'Нулевое')], default='new', max_length=16, verbose_name='Статус')),
                ('expense', models.IntegerField(verbose_name='Показания счетчика')),
            ],
            options={
                'verbose_name': 'Показание счетчика',
                'verbose_name_plural': 'Показания счетчика',
            },
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_number', models.BigIntegerField(default=crm.models.personal_account_number, unique=True, verbose_name='Номер лицевого счета')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=16, verbose_name='Статус')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Остаток (грн.)')),
            ],
            options={
                'verbose_name': 'Лицевой счет',
                'verbose_name_plural': 'Лицевые счета',
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название компании')),
                ('information', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Услуга')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать в счетчиках')),
                ('currency', models.CharField(blank=True, default='грн', max_length=4, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceForInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_for_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за ед., грн.')),
                ('expense', models.IntegerField(verbose_name='Расход')),
                ('full_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость, грн.')),
            ],
            options={
                'verbose_name': 'Услуга для квитанции',
                'verbose_name_plural': 'Услуги для квитанций',
            },
        ),
        migrations.CreateModel(
            name='ServiceForTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_for_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга для тарифа',
                'verbose_name_plural': 'Услуги для тарифоф',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название тарифа')),
                ('description', models.TextField(verbose_name='Описание тарифа')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='files/', verbose_name='Загрузить пользовательский шаблон')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('is_default', models.BooleanField(blank=True, default=False, verbose_name='По-умолчанию')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=crm.models.transaction_number, unique=True, verbose_name='Номер ведомости')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('completed', models.BooleanField(default=True, verbose_name='Проведен')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_income', models.BooleanField(default=True, verbose_name='Приходная ведомость')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.item', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Приход/Расход',
                'verbose_name_plural': 'Приходные/Расходные ведомости',
            },
        ),
    ]
