# Generated by Django 3.2 on 2022-07-01 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец квартиры'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='personal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.personalaccount', verbose_name='Лицевой счет'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='services',
            field=models.ManyToManyField(through='crm.ServiceForTariff', to='crm.Service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='servicefortariff',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='servicefortariff',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.tariff', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='serviceforinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.invoice', verbose_name='Квитанция'),
        ),
        migrations.AddField(
            model_name='serviceforinvoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.unit', verbose_name='Ед. изм.'),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.apartment', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.apartment', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.service', verbose_name='Счетчик'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.apartment', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(through='crm.ServiceForInvoice', to='crm.Service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.tariff', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='house',
            name='floors',
            field=models.ManyToManyField(to='crm.Floor', verbose_name='Этажи'),
        ),
        migrations.AddField(
            model_name='house',
            name='sections',
            field=models.ManyToManyField(to='crm.Section', verbose_name='Секции'),
        ),
        migrations.AddField(
            model_name='house',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='application',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.apartment', verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='application',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.floor', verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.section', verbose_name='Секция'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterUniqueTogether(
            name='servicefortariff',
            unique_together={('tariff', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceforinvoice',
            unique_together={('invoice', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('floor', 'number')},
        ),
    ]
