# Generated by Django 3.2 on 2022-07-01 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_before',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Период до'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_with',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Период с'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
