# Generated by Django 3.2 on 2022-07-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20220701_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(blank=True, default='грн', max_length=4, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='servicefortariff',
            name='cost_for_unit',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='Единица измерения'),
        ),
    ]
