# Generated by Django 3.2 on 2022-07-16 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20220712_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefortariff',
            name='tariff',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crm.tariff', verbose_name='Тариф'),
        ),
    ]
