# Generated by Django 3.2 on 2022-07-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20220725_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalaccount',
            old_name='number',
            new_name='personal_number',
        ),
    ]
