# Generated by Django 3.2 on 2022-08-01 13:21

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0007_rename_number_personalaccount_personal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.apartment', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='personal_number',
            field=models.BigIntegerField(default=crm.models.personal_account_number, unique=True, verbose_name='Номер лицевого счета'),
        ),
    ]
