# Generated by Django 3.2 on 2022-08-03 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0009_remove_application_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128, verbose_name='Тема сообщения')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('is_debt', models.BooleanField(default=False, verbose_name='Владельцам с задолженностями')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.apartment', verbose_name='Квартира')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.floor', verbose_name='Этаж')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.house', verbose_name='ЖК')),
                ('message_for_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_for_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец квартиры')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.section', verbose_name='Секция')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
