# Generated by Django 3.2 on 2022-08-03 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.apartment', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='message',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='message',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.house', verbose_name='ЖК'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_for_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_for_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец квартиры'),
        ),
        migrations.AlterField(
            model_name='message',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.section', verbose_name='Секция'),
        ),
    ]
