# Generated by Django 3.2 on 2022-08-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачена'), ('p_paid', 'Частично оплачена'), ('unpaid', 'Неоплачена')], default='paid', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='serviceforinvoice',
            name='cost_for_unit',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за ед., грн.'),
        ),
        migrations.AlterField(
            model_name='serviceforinvoice',
            name='full_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость, грн.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
