# Generated by Django 3.2 on 2022-08-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20220805_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_account', to='crm.apartment', verbose_name='Квартира'),
        ),
    ]
