# Generated by Django 3.2 on 2022-08-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_personalaccount_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='serviceforinvoice',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.invoice', verbose_name='Квитанция'),
        ),
    ]
