# Generated by Django 3.2 on 2022-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20220810_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to='files/', verbose_name='Загрузить пользовательский шаблон')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('is_default', models.BooleanField(default=False, verbose_name='По-умолчанию')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
    ]
